# -*- coding: utf-8 -*-
"""p114

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hndd4RGbDuyWzwazdOD7Fm6HPD3zCbqM
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv("data.csv")
toelf_score=df["TOEFL Score"].tolist()
chances_of_admit=df["Chance of Admit "].tolist()
fig=px.scatter(x=toelf_score,y=chances_of_admit)
fig.show()

m=0.01
c=-2.5
y=[]
for x in toelf_score :
  y_value=m*x+c
  y.append(y_value)
fig=px.scatter(x=toelf_score,y=chances_of_admit)
fig.update_layout(shapes=[
    dict(
        type='line',
         y0=min(y),y1=max(y),
         x0=min(toelf_score),x1=max(toelf_score))
])
fig.show()

x=250
y=m*x+c
print(f"chances of admition a student based on toelf_score:- {x} is {y} ")

import numpy as np
toelf_score_array=np.array(toelf_score)
chances_of_admit_array=np.array(chances_of_admit)
m,c=np.polyfit(toelf_score_array,chances_of_admit_array,1)
y=[]
for x in toelf_score_array:
    y_value=m*x+c
    y.append(y_value)
fig=px.scatter(x=toelf_score_array,y=chances_of_admit_array)
fig.update_layout(shapes=[
    dict(
        type='line',
         y0=min(y),y1=max(y),
         x0=min(toelf_score_array),x1=max(toelf_score_array))
])
fig.show()

x=250
y=m*x+c
print(f"chances of admition a student based on toelf_score:- {x} is {y} ")